### ISSUE TITLE
Lavaproof Fishing Hook Tick Exception

### ISSUE THREAD

**Issue by zeroneon** [Lightning-64/Tide#37] opened 2024-11-04 19:59 UTC
Whenever I try to fish with a Lavaproof Fishing Hook in water this exception is thrown:
java.lang.IllegalArgumentException: bound must be greater than origin
	at java.base/jdk.internal.util.random.RandomSupport.checkRange(RandomSupport.java:232)
	at java.base/java.util.random.RandomGenerator.nextInt(RandomGenerator.java:679)
	at TRANSFORMER/tide@1.3.4/com.li64.tide.registries.entities.misc.fishing.TideFishingHook.selectCatch(TideFishingHook.java:687)
	at TRANSFORMER/tide@1.3.4/com.li64.tide.registries.entities.misc.fishing.TideFishingHook.catchingFish(TideFishingHook.java:433)
	at TRANSFORMER/tide@1.3.4/com.li64.tide.registries.entities.misc.fishing.TideFishingHook.m_8119_(TideFishingHook.java:289)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8647_(ServerLevel.java:693)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$172(Level.java)
	at TRANSFORMER/neruina@2.0.0-beta.10/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:91)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.wrapOperation$fff000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:8540)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_184063_(ServerLevel.java:343)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:323)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:893)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:840)
	
Minecraft 1.20.1 on Forge (Tide 1.3.4)

I was using the Netherite Fishing Rod with a Lavaproof Fishing Hook in the End in water.

**Comment by zeroneon** [comment] 2024-11-04 20:02
For anyone testing this out, I heavily recommend installing Neruina (https://github.com/Bawnorton/Neruina) to make it easier

**Comment by JasdewStarfield** [comment] 2024-11-05 05:46
I have also encountered a similar problem when I was fishing in the Undergarden (added by mod the Undergarden), and at that time I thought it was caused by that mod. (But now it seems that it there's something wrong with Tide's fishing loot tables?)

**Comment by Lightning-64** [comment] 2024-12-05 14:44
Should be fixed once 1.4 comes out

**Closed by Lightning-64** 2024-12-05 14:44 UTC
Labels: bug
